CREATE TABLE EMPLOYEE(NAME CHAR(10),EMP_ID INT(10), PRIMARY KEY(EMP_ID));
INSERT INTO EMPLOYEE VALUES
('MEENU','255'),('KICHU','110');
CREATE TABLE EMPLOYEE_DETAILS(EMP_ID INT(10), DEPARTMENT CHAR(10));
INSERT INTO EMPLOYEE_DETAILS VALUES
('88','MANAGER'),('255','CLERK');
SELECT * 
FROM EMPLOYEE
WHERE EMP_ID IN
( SELECT EMP_ID 
 FROM EMPLOYEE_DETAILS);
 SELECT *
 FROM EMPLOYEE
 WHERE EMP_ID NOT IN
 ( SELECT * EMP_ID 
  FROM EMPLOYEE_DETAILS);
